import create from "./channel/create"
import show from "./channel/show"
import update from "./channel/update"
import join from "./channel/join"
import leave from "./channel/leave"
import joined from "./channel/joined"
import attribute from "./channel/attribute"
import permissions from "./channel/permissions"
import members from "./channel/members"
export default { create, show, update, join, leave, joined, attribute, members, permissions }