import show from "./channel/show"
import join from "./channel/join"
import invite from "./channel/invite"
import kick from "./channel/kick"
import create from "./channel/create"
import update from "./channel/update"
import attribute from "./channel/attribute"
import members from "./channel/members"
import permissions from "./channel/permissions"
export default { show, join, invite, kick, create, update, attribute, members, permissions }