import account from "./account"
import server from "./server"
import hashtag from "./hashtag"
import user from "./user"
import like from "./like"
import media from "./media"
import favorite from "./favorite"
import reaction from "./reaction"
import status from "./status"
import access_token from "./access_token"
export default { account, server, hashtag, user, like, media, status, reaction, favorite, access_token }