import status from "./status"
import user from "./user"
import server from "./server"
import hashtag from "./hashtag"
import timeline from "./timeline"
import media from "./media"
import account from "./account"
import like from "./like"
import favorite from "./favorite"
import reaction from "./reaction"
export default { status, user, server, hashtag, timeline, media, account, like, reaction, favorite }